# sheldon プラグイン設定ファイル
# https://github.com/rossmacarthur/sheldon

shell = "zsh"

# zsh-autosuggestions - コマンド履歴の自動補完
[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# zsh-z - ディレクトリジャンプ
[plugins.zsh-z]
github = "agkozak/zsh-z"

# fzf - ファジーファインダー
[plugins.fzf]
github = "junegunn/fzf"

# powerlevel10k - テーマ
[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

# zsh-syntax-highlighting - シンタックスハイライト
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

